from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name='Advertisement',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('slot',models.CharField(choices=[('left_top','Left Top'),('right_top','Right Top'),('right_bottom','Right Bottom'),('featured','Featured')],max_length=30)),('business_name',models.CharField(max_length=160)),('image',models.URLField(blank=True)),('target_url',models.URLField(blank=True)),('start_date',models.DateField(blank=True,null=True)),('end_date',models.DateField(blank=True,null=True)),('priority',models.PositiveIntegerField(default=0)),('active',models.BooleanField(default=True))],options={'ordering':['slot','-priority','business_name']}),
        migrations.CreateModel(name='HistoricalDate',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('gregorian',models.DateField(unique=True)),('bengali_day',models.PositiveSmallIntegerField(blank=True,null=True)),('bengali_month',models.CharField(blank=True,max_length=40)),('bengali_year',models.PositiveIntegerField(blank=True,null=True)),('santali_day',models.PositiveSmallIntegerField(blank=True,null=True)),('santali_month',models.CharField(blank=True,max_length=80)),('santali_year',models.PositiveIntegerField(blank=True,null=True)),('note',models.TextField(blank=True))],options={'ordering':['gregorian']}),
        migrations.CreateModel(name='LunarEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('month_order',models.PositiveSmallIntegerField()),('day',models.PositiveSmallIntegerField()),('title',models.CharField(max_length=200)),('description',models.TextField(blank=True)),('image',models.URLField(blank=True)),('label',models.CharField(blank=True,max_length=80)),('active',models.BooleanField(default=True))],options={'ordering':['month_order','day','title']}),
        migrations.CreateModel(name='LunarMonth',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('order',models.PositiveSmallIntegerField(unique=True)),('olchiki_name',models.CharField(max_length=80)),('english_name',models.CharField(max_length=40)),('is_extra',models.BooleanField(default=False)),('active',models.BooleanField(default=True))],options={'ordering':['order']}),
        migrations.CreateModel(name='NewMoon',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField(unique=True)),('lunar_year',models.PositiveIntegerField(blank=True,null=True)),('month_order',models.PositiveSmallIntegerField(blank=True,null=True)),('note',models.CharField(blank=True,max_length=255))],options={'ordering':['date']}),
        migrations.CreateModel(name='SiteSetting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('key',models.CharField(max_length=80,unique=True)),('value',models.TextField(blank=True))]),
        migrations.CreateModel(name='SolarEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('date',models.DateField()),('title',models.CharField(max_length=200)),('short_description',models.CharField(blank=True,max_length=300)),('details',models.TextField(blank=True)),('image',models.URLField(blank=True)),('active',models.BooleanField(default=True))],options={'ordering':['date']}),
    ]
