# Generated by Django 5.2.17 on 2026-09-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunarmonth',
            name='english_name',
            field=models.CharField(max_length=60),
        ),
    ]
