# Generated by Django 6.1 on 2026-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_lunarmonth_english_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunarevent',
            options={'ordering': ['month_order', 'day_from', 'title']},
        ),
        migrations.RemoveField(
            model_name='lunarevent',
            name='day',
        ),
        migrations.AddField(
            model_name='lunarevent',
            name='day_from',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lunarevent',
            name='day_to',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lunarevent',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='solarevent',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
