# Generated by Django 6.1 on 2026-09-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_lunarevent_options_remove_lunarevent_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='solarevent',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
